### Tensorflow

In [171]:
import tensorflow as tf

#### Create

In [ ]:
random_tf = tf.random.normal(shape=(3, 4), seed=42) 
random_tf

#### Read

In [178]:
tf_random_var = tf.Variable(tf_rand) 
tf_random_var

<tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[-2.3159974 , -0.07912122, -0.8998717 ,  0.31664512],
       [-1.1119006 ,  1.3949379 ,  0.4992896 , -1.461813  ],
       [-0.7174765 , -0.4182692 , -2.1247718 ,  1.7517222 ]],
      dtype=float32)>

#### Update

In [179]:
tf_random_var[0, 0].assign(1000) 
tf_random_var 

<tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[ 1.0000000e+03, -7.9121225e-02, -8.9987171e-01,  3.1664512e-01],
       [-1.1119006e+00,  1.3949379e+00,  4.9928960e-01, -1.4618130e+00],
       [-7.1747649e-01, -4.1826919e-01, -2.1247718e+00,  1.7517222e+00]],
      dtype=float32)>

#### Delete

In [184]:
num = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=(2, 3)) 
vectors = tf.unstack(num, axis=1) 
del vectors[1] 
num_new = tf.stack(vectors, 1) 
num_new 

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 3.],
       [4., 6.]], dtype=float32)>

#### To numpy

In [180]:
tf_random_var.numpy() 

array([[ 1.0000000e+03, -7.9121225e-02, -8.9987171e-01,  3.1664512e-01],
       [-1.1119006e+00,  1.3949379e+00,  4.9928960e-01, -1.4618130e+00],
       [-7.1747649e-01, -4.1826919e-01, -2.1247718e+00,  1.7517222e+00]],
      dtype=float32)

#### Reshape

In [181]:

tf_rand_var_reshaped = tf.reshape(tf_rand_var, (6, 2))
tf_rand_var_reshaped

<tf.Tensor: shape=(6, 2), dtype=float32, numpy=
array([[ 1.0000000e+03, -7.9121225e-02],
       [-8.9987171e-01,  3.1664512e-01],
       [-1.1119006e+00,  1.3949379e+00],
       [ 4.9928960e-01, -1.4618130e+00],
       [-7.1747649e-01, -4.1826919e-01],
       [-2.1247718e+00,  1.7517222e+00]], dtype=float32)>